apiVersion: v1
kind: Pod
metadata:
  name: alert-pod
  labels:
    name: alert-pod # which can be the same name as pod (the metadata name)
    app: cc2023w # name of the applicaton
spec:
  containers:
    - name: alert
      image: ccuni/alert-service-2023w
      ports:
        - containerPort: 80 # the port on which the application listens
