apiVersion: v1
kind: Pod
metadata:
  name: camera-pod
  labels:
    name: camera-pod # which can be the same name as pod (the metadata name)
    app: cc2023w # name of the applicaton
spec:
  containers:
    - name: camera
      image: ccuni/camera-service-2023w
      ports:
        - containerPort: 80 # the port on which the application listens
