apiVersion: v1
kind: Pod
metadata:
  name: collector-pod
  labels:
    name: collector-pod # which can be the same name as pod (the metadata name)
    app: cc2023w # name of the applicaton
spec:
  containers:
    - name: collector
      image: sussap/collector_prac:latest
      ports:
        - containerPort: 80 # the port on which the application listens
      env:
        - name: IMAGE_ANALYSIS_URL
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: IMAGE_ANALYSIS_URL
        - name: FACE_RECOGNITION_URL
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: FACE_RECOGNITION_URL
        - name: ALERT_URL
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: ALERT_URL
        - name: SECTION_URL
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: SECTION_URL
