apiVersion: v1
kind: Pod
metadata:
  name: face-recognition-pod
  labels:
    name: face-recognition-pod # which can be the same name as pod (the metadata name)
    app: cc2023w # name of the applicaton
spec:
  containers:
    - name: face-recognition
      image: ccuni/face-recognition-service-2023w
      ports:
        - containerPort: 80 # the port on which the application listens
