apiVersion: v1
kind: Pod
metadata:
  name: image-analysis-pod
  labels:
    name: image-analysis-pod # which can be the same name as pod (the metadata name)
    app: cc2023w # name of the applicaton
spec:
  containers:
    - name: image-analysis
      image: ccuni/image-analysis-service-2023w
      ports:
        - containerPort: 80 # the port on which the application listens
