apiVersion: v1
kind: Pod
metadata:
  name: mongo-express-pod
  labels:
    name: mongo-express-pod
    app: cc2023w
spec:
  containers:
    - name: mongo-express
      image: mongo-express
      ports:
        - containerPort: 27017
      env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: environment-secret
              key: ME_CONFIG_MONGODB_ADMINUSERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: environment-secret
              key: ME_CONFIG_MONGODB_ADMINPASSWORD
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: ME_CONFIG_MONGODB_SERVER
