apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deploy
  labels:
    name: collector-deploy
    app: cc2023w
spec:
  replicas: 1
  selector:
    matchLabels:
      name: collector-pod
      app: cc2023w
  template:
    metadata:
      name: collector-pod
      labels:
        name: collector-pod
        app: cc2023w
    spec:
      containers:
        - name: collector
          image: sussap/collector_prac:collector_v2
          ports:
            - containerPort: 80
          env:
            - name: IMAGE_ANALYSIS_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: IMAGE_ANALYSIS_URL
            - name: FACE_RECOGNITION_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: FACE_RECOGNITION_URL
            - name: ALERT_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: ALERT_URL
            - name: SECTION_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: SECTION_URL
---
apiVersion: v1
kind: Service
metadata:
  name: collector-service # this is the name of service
  labels:
    name: collector-service
    app: cc2023w
spec:
  ports:
    - port: 8000
      targetPort: 80
  # in order to link the service to the pod, we have to specify same labels configured for pod
  selector:
    name: collector-pod
    app: cc2023w
